### ISSUE TITLE
Restore oscillation status

### ISSUE THREAD

**Issue by ReX1983** [NicoIIT/esphome-components#1]
Hello,

You really did an amazing job here: this component made possible to integrate into Home Assistant an otherwise dumb fan/lamp.

I have a small request: is it possible to restore the previous oscillation status (instead of resetting to off), when the fan turns off?

Something like:

```
  - platform: ble_adv_controller
      ble_adv_controller_id: my_controller
      id: my_fan
      name: My Fan
      on_turn_on:
        then:
          fan.turn_on:
            id: my_fan
            oscillating: <restore latest>
```

I can do that in HA (with automation), but it would be nicer if dealt from the ESP32.

Thanks!

**Comment by ReX1983** [comment]
I find odd these lamps save and restore the fan speed but not the oscillation (mine can't reverse the flow). I wonder why. 

Anyway, before finding your amazing component, I had a very hacky way to handle the lamp, that consisted in piloting the lamp remote with and ESP32 :-). I hated it but it did the job. In doing so, I had to restore the state on each turn on with a sequence of commands for speed, fan light and oscillation (from Home Assistant) and hence I can now restore the oscillation from HA, but it would be neater to do it from ESPHome.

**Comment by ReX1983** [comment]
Mmm... I am having an issue when trying to update, validate and install the new config:
```

INFO ESPHome 2024.7.3
INFO Reading configuration /config/esphome/loft-ceiling-fan-lamp.yaml...
ERROR Unable to load component ble_adv_controller.fan:
Traceback (most recent call last):
  File "/esphome/esphome/loader.py", line 176, in _lookup_module
    module = importlib.import_module(f"esphome.components.{domain}")
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/data/external_components/a7b2aad8/components/ble_adv_controller/fan/__init__.py", line 36
    ).extend(ENTITY_BASE_CONFIG_SCHEMA),
    ^
SyntaxError: closing parenthesis ')' does not match opening parenthesis '{' on line 28
Failed config

fan.ble_adv_controller: [source /config/esphome/loft-ceiling-fan-lamp.yaml:360]
  
  Platform not found: 'fan.ble_adv_controller'.
  platform: ble_adv_controller
  ble_adv_controller_id: loft_ceiling_fan_lamp_controller
  name: Loft Ceiling Fan
  speed_count: 6
  use_direction: False
  use_oscillation: True
  forced_refresh_on_start: True
```

Any idea?

**Comment by NicoIIT** [comment]
Oups sorry, typo on last change ...
Corrected!

**Comment by ReX1983** [comment]
Tested quickly: everything works as expected. No regression. The fan restores the previous oscillation status, when turned on.

The only odd thing I have noticed is that, while on, at any command to change the fan speed, the fan responds two confirmation sounds. Is this because each time we set the speed we also send a set oscillation command?

I see the same behaviour at turn on (expected, as we want to restore the oscillation state). Single sound when turning off (also expected). 

Not a big deal, but is there a way to avoid sending the double command when changing speed while the fan is on? It seems uncessessary.

**Comment by NicoIIT** [comment]
Ahah indeed you spotted exactly the problem, corrected!

**Comment by ReX1983** [comment]
Just tested - all working as expected 🥇 !

**Comment by ReX1983** [comment]
@NicoIIT , was there any recent change in this area? The restore functionality doesn't seem to work anymore.

I am on ESPHome 2025.2.0 and your latest release.

**Comment by NicoIIT** [comment]
@ReX1983 : there was thousands of changes since this one !!!

The only thing that may explains it does not work anymore for you is that the default value for the option "forced_refresh_on_start" is now "false" (due to [side effect](https://github.com/NicoIIT/esphome-components/issues/2) on other users). Doc [here](https://github.com/NicoIIT/esphome-components/blob/main/components/ble_adv_controller/README.md#configuration-for-fan).

Note that you can now [reset the HA state](https://github.com/NicoIIT/esphome-components/blob/main/components/ble_adv_controller/README.md#action-on-turn-onoff) at stop time if it is more easy.

**Comment by ReX1983** [comment]
I can see you have been busy!

So, my yaml has still forced_refresh_on_start set to true. Everything else works, but on start I can't hear the second confirmation sound, so the second command is not sent.

I could set to false oscillating when the fan goes off, but I would rather keep the previous setting.

Any idea?

**Comment by NicoIIT** [comment]
@ReX1983 , there might be some concurrency in between the commands (Fan ON / Fan set oscillation) that are sent one after the other. Try to increase the 'duration' to the maximum 500 from the HA config; If it works you can then decrease it step by step to find the best value.

**Comment by ReX1983** [comment]
> [@ReX1983](https://github.com/ReX1983) , there might be some concurrency in between the commands (Fan ON / Fan set oscillation) that are sent one after the other. Try to increase the 'duration' to the maximum 500 from the HA config; If it works you can then decrease it step by step to find the best value.

Mmm...  unfortunately it doesn't work. No sign of second command. Any idea? Please let me know if (and how) I can provide some debug info.

This is my fan configuration, anything wrong with it?

```
fan:
  - platform: ble_adv_controller
    ble_adv_controller_id: loft_ceiling_fan_lamp_controller
    name: Loft Ceiling Fan
    speed_count: 6
    use_direction: false
    use_oscillation: true
    forced_refresh_on_start: true
```

**Comment by NicoIIT** [comment]
@ReX1983 , There is nothing wrong with your config, I have the same and the messages are properly sent, but the second one is going out too fast and not taken into account by your device.

I increased the maximum for the 'duration' from 500ms to 1s, so please retry to put the max for this parameter from HA configuration slider.

**Comment by ReX1983** [comment]
> I increased the maximum for the 'duration' from 500ms to 1s, so please retry to put the max for this parameter from HA configuration slider.

Finally managed to test it and you are right, it was a race condition issue. Anything below 800msec causes the second command to get missed. I wonder how it used to work before.

I am keeping it at 900, for safety.

Thanks again!

**Comment by NicoIIT** [comment]
I think I found the reason of this change: the default value for `max_duration` has been decreased because a high value was slowing down some users with multiple controllers on a same ESP. 

I re read my own documentation concerning [durations](https://github.com/NicoIIT/esphome-components/blob/main/components/ble_adv_controller/README.md#durations) and in fact this setting could have an impact on your case, as in your case you have the following:
* A first transaction is issued: Fan ON. It is emitted during a minimum `duration` (as a second transaction is issued immediately): `[ t -> t + duration ]`
* A second transaction is issued: Fan Oscillation (or direction). It is emitted during `max_duration` (as no other transaction is issued afterwards) `[ t + duration -> t + duration + max_duration ]`

If we consider `min_device_time` the time needed by your device to handle a transaction, and that it handles the first  transaction immediately at `t`, it will handle the second transaction if:
`min_device_time < duration + max_duration`

As a consequence:
* the decrease of `max_duration` (default value) caused the change
* the increase of `duration` solved it
* the increase of `max_duration` will also solve it

Still this `max_duration` is a duplication of what the phone apps are doing but it is a bit of a nonsense as it makes the behavior of a transaction changing depending on the transaction that follows... On the [HA version](https://github.com/NicoIIT/ha-ble-adv) (available for beta tests btw 😃) I am working on, I removed it.
